/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IVaultNFT } from "../IVaultNFT";

export class IVaultNFT__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVaultNFT {
    return new Contract(address, _abi, signerOrProvider) as IVaultNFT;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
